chore(tsconfig): use commonjs to resolve errors in github-bot.ts
api/github-bot.ts(5,18): error TS1479: The current file is a CommonJS
  module whose imports will produce 'require' calls; however, the
  referenced file is an ECMAScript module and cannot be imported with
  'require'. Consider writing a dynamic 'import("@commitlint/lint")'
  call instead.
To convert this file to an ECMAScript module, change its file
  extension to '.mts', or add the field `"type": "module"` to
  'package.json'.
api/github-bot.ts(6,24): error TS1479: The current file is a CommonJS
  module whose imports will produce 'require' calls; however, the
  referenced file is an ECMAScript module and cannot be imported with
  'require'. Consider writing a dynamic 'import("@commitlint/format")'
  call instead.
To convert this file to an ECMAScript module, change its file
  extension to '.mts', or add the field `"type": "module"` to
  'package.json'.
api/github-bot.ts(7,46): error TS1479: The current file is a CommonJS
  module whose imports will produce 'require' calls; however, the
  referenced file is an ECMAScript module and cannot be imported with
  'require'. Consider writing a dynamic 'import("@commitlint/types")'
  call instead.
To convert this file to an ECMAScript module, change its file
  extension to '.mts', or add the field `"type": "module"` to
  'package.json'.